


import {Contact} from "./contact";


export const Contacts: Contact[] = [
  {
    id:1,
    firstName : "Deus Ex",
    middleName: " Xbox",
    lastName: " Xbox One, PS4, PC",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "123456",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:2,
    firstName : "Deus Ex",
    middleName: " Xbox ",
    lastName: " Xbox",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "123456789",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:3,
    firstName : "Deus Ex",
    middleName: " Xbox ",
    lastName: " Xbox ",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "123456789",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:4,
    firstName : "Deus Ex",
    middleName: " Xbox",
    lastName: " Xbox ",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "12323456789",
    socialNetworkingProfiles:" Xbox",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:5,
    firstName : "Deus Ex",
    middleName: " Xbox",
    lastName: " Xbox",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "122345678",
    socialNetworkingProfiles:" Xbox ",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:6,
    firstName : "Deus Ex",
    middleName: " Xbox ",
    lastName: " Xbox ",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "1323456789",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:7,
    firstName : "Deus Ex",
    middleName: " Xbox",
    lastName: " Xbox One, PS4, PC",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: "123456789",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:8,
    firstName : "Deus Ex",
    middleName: " Xbox One, PS4, PC",
    lastName: " Xbox One, PS4, PC",
    companyName: " Xbox One, PS4, PC",
    department: " Xbox One, PS4, PC",
    title: " Xbox One, PS4, PC",
    email: "Xbox One, PS4, PC",
    phoneNumber: " 1234567",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " Xbox One, PS4, PC",
    addressLine2: " Xbox One, PS4, PC",
    city: " Xbox One, PS4, PC",
    state: " Xbox One, PS4, PC",
    zipCode: " Xbox One, PS4, PC",
    country : "USA"
  },
  {
    id:10,
    firstName : "John",
    middleName: " X",
    lastName: " Smith",
    companyName: " ABC",
    department: " Y",
    title: " Boss",
    email: "Xbox One, PS4, PC",
    phoneNumber: " 1234576890",
    socialNetworkingProfiles:" Xbox One, PS4, PC",
    addressLine1: " 1000 N 4th Street",
    addressLine2: " #125",
    city: "Fairfield",
    state: "Iowa",
    zipCode: " 52557",
    country : "USA"
  }
];
